import { StrictMode, useEffect, useState, lazy, Suspense } from 'react';
import { createRoot } from 'react-dom/client';
import { FileText, Users, Palette, Settings, Code2, LogOut, ArrowRight, ChevronRight, Check, X, Menu, LockKeyhole, ShieldCheck } from 'lucide-react';
import { api, body, setCsrf } from './api';
import { Editor } from './editor';
import { ApiPage, Customers, Invoices, Presets, SettingsPage } from './pages';
import './styles.css';

const SharedInvoice = lazy(() => import('./shared-invoice'));
function App() {
  const [authenticated, setAuthenticated] = useState(false); const [checking, setChecking] = useState(true); const [path, setPath] = useState(location.pathname); const [mobileMenu, setMobileMenu] = useState(false);
  const [toast, setToast] = useState<{ message: string; error: boolean }>();
  const notify = (message: string, error = false) => setToast({ message, error });
  useEffect(() => { const timer = toast ? setTimeout(() => setToast(undefined), toast.error ? 12000 : 5000) : undefined; return () => clearTimeout(timer); }, [toast]);
  useEffect(() => {
    if (location.pathname.startsWith('/s/')) { setChecking(false); return; }
    api<{ csrfToken: string }>('/auth/session').then(r => { setCsrf(r.csrfToken); setAuthenticated(true); }).catch(() => {}).finally(() => setChecking(false));
    const pop = () => setPath(location.pathname); const expire = () => { setAuthenticated(false); setCsrf(''); notify('Your session expired. Sign in again.', true); };
    window.addEventListener('popstate', pop); window.addEventListener('session-expired', expire); return () => { window.removeEventListener('popstate', pop); window.removeEventListener('session-expired', expire); };
  }, []);
  function navigate(next: string) { history.pushState(null, '', next); setPath(next); setMobileMenu(false); window.scrollTo(0, 0); }
  const nav = [{ path: '/', label: 'Invoices', icon: FileText }, { path: '/customers', label: 'Customers', icon: Users }, { path: '/presets', label: 'Branding presets', icon: Palette }, { path: '/settings', label: 'Business settings', icon: Settings }, { path: '/api', label: 'Developer API', icon: Code2 }];
  const current = path === '/new' || path.startsWith('/invoices/') ? '/' : path;
  return <>{path.startsWith('/s/') ? <Suspense fallback={<div className="loading-state">Opening invoice…</div>}><SharedInvoice token={path.split('/')[2]} /></Suspense> : checking ? <div className="app-loading"><span className="brand-mark"><FileText size={22} /></span>Getting things ready…</div> : !authenticated ? <Login onLogin={csrf => { setCsrf(csrf); setAuthenticated(true); }} /> : <div className="app-shell"><button className="mobile-menu button" aria-label="Toggle menu" onClick={() => setMobileMenu(!mobileMenu)}><Menu size={20} /> Invoicer</button><aside className={`sidebar ${mobileMenu ? 'open' : ''}`}><a className="brand" href="/" onClick={e => { e.preventDefault(); navigate('/'); }}><span className="brand-mark"><FileText size={22} strokeWidth={1.8} /></span>invoicer<span className="brand-dot">.</span></a><div className="workspace-label"><span className="workspace-avatar">YB</span><div><strong>Your business</strong><small>Private workspace</small></div><LockKeyhole size={13} /></div><span className="nav-caption">WORKSPACE</span><nav>{nav.map(n => <a key={n.path} href={n.path} className={current === n.path ? 'active' : ''} onClick={e => { e.preventDefault(); navigate(n.path); }}><n.icon size={18} /><span>{n.label}</span>{current === n.path && <ChevronRight size={14} />}</a>)}</nav><div className="sidebar-bottom"><div className="ownership-note"><ShieldCheck size={20} /><strong>Small by design.</strong><p>Open source. Self hosted.<br />Entirely yours.</p></div><button className="logout" onClick={() => void api('/auth/logout', { method: 'POST' }).then(() => { setAuthenticated(false); setCsrf(''); }).catch(e => notify(e.message, true))}><LogOut size={16} /> Sign out</button><span className="sidebar-version">INVOICER · v0.1.0</span></div></aside><div className="main-shell"><header className="topbar"><span>Workspace <ChevronRight size={13} /><strong>{nav.find(n => n.path === current)?.label || 'Invoices'}</strong></span><span className="private-tag"><span className="tiny-dot" /> Your account. Your data.</span></header><main key={path}>{path === '/new' || path.startsWith('/invoices/') ? <Editor key={path} id={path.startsWith('/invoices/') ? path.split('/')[2] : undefined} navigate={navigate} notify={notify} /> : path === '/customers' ? <Customers navigate={navigate} notify={notify} /> : path === '/presets' ? <Presets navigate={navigate} notify={notify} /> : path === '/settings' ? <SettingsPage navigate={navigate} notify={notify} /> : path === '/api' ? <ApiPage /> : <Invoices navigate={navigate} notify={notify} />}</main></div></div>}{toast && <div className={`toast ${toast.error ? 'error' : ''}`} role={toast.error ? 'alert' : 'status'}>{toast.error ? <X size={18} /> : <Check size={18} />}<span>{toast.message}</span><button aria-label="Dismiss notification" onClick={() => setToast(undefined)}><X size={16} /></button></div>}</>;
}
function Login({ onLogin }: { onLogin: (csrf: string) => void }) {
  const [key, setKey] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function login(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const r = await api<{ csrfToken: string }>('/auth/login', { method: 'POST', body: body({ key }) }); setKey(''); onLogin(r.csrfToken); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="login-page"><div className="login-left"><a className="brand" href="/"><span className="brand-mark"><FileText size={22} /></span>invoicer<span className="brand-dot">.</span></a><div className="login-copy"><span className="eyebrow">YOUR BUSINESS, ON PAPER</span><h1>Good work.<br />Great invoices.</h1><p>A thoughtful little workspace for the business you’re building. Create, customize, and share invoices that feel like you.</p><div className="login-benefits"><span><Check size={15} /> Your logo. Your style.</span><span><Check size={15} /> A simple, powerful API.</span><span><Check size={15} /> Hosted on your own account.</span></div></div><div className="login-paper-art" aria-hidden="true"><div className="art-paper"><span className="art-wordmark">YOUR BUSINESS</span><strong>INVOICE</strong><div className="art-address"><i /><i /><i /></div><div className="art-table"><b /><span /><span /><span /></div><div className="art-total">TOTAL <b>1,250.00</b></div><span className="art-thanks">Thank you for your business.</span></div><div className="art-badge"><ShieldCheck size={17} /> Entirely yours</div></div><footer>Open source. Self hosted. Small by design.</footer></div><div className="login-right"><form className="login-form" onSubmit={e => void login(e)}><span className="login-lock"><LockKeyhole size={23} /></span><h2>Welcome to your workspace.</h2><p>Sign in with your business’s admin key.</p><label className="field"><span>Admin key</span><input type="password" required autoComplete="current-password" value={key} onChange={e => setKey(e.target.value)} placeholder="Enter your admin key" /></label>{error && <div className="inline-error" role="alert">{error}</div>}<button className="button primary full" disabled={busy}>{busy ? 'Signing in…' : 'Open workspace'}<ArrowRight size={17} /></button><div className="login-security"><LockKeyhole size={13} /> No customer accounts. Just one key for your business.</div></form></div></div>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
